language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libgcrypt
            - libgcrypt-devel
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         

before_install:
 - eval "${MATRIX_EVAL}"
 
script:
  - python attack_libgcrypt.py
